=== Georges034302/WSD/WSD-lab-demo/web/WEB-INF/users.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.uts.edu.au/31284/wsd-users"
    xmlns="http://www.uts.edu.au/31284/wsd-users"
    elementFormDefault="qualified">
    
    <xs:simpleType name="passwordType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z]{6,})(\d{2,})"/>
        </xs:restriction>        
    </xs:simpleType>
      
    <xs:simpleType name="phoneType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\(((0)[1-9])\)(\s)(\d{4}-[0-9]{4})"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="password" type="passwordType"/>
                            <xs:element name="phone" type="phoneType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Georges034302/WSD/lab_demo/web/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="users.xsl"?>

<users xmlns="http://www.uts.edu.au/31284/wsd-users"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-users users.xsd">
    <user>
        <name>Ryan Bradley</name>
        <email>ryan@bradley.com</email>      
        <password>blahblah88</password> 
        <phone>(02) 9999-1111</phone>       
    </user>
    <user>
        <name>Joe Bloggs</name>
        <email>joe@bloggs.com</email>        
        <password>foobar222</password>     
        <phone>(04) 2288-1122</phone>   
    </user>
    <user>
        <name>Georges Bou Ghantous</name>
        <email>georges.boughantous@gmail.com</email>    
        <password>tutorial124</password>    
        <phone>(03) 1234-0000</phone>         
    </user>  
    <user>
        <name>Joe Bloggs</name>
        <email>joe@bloggs.com</email>        
        <password>foobar222</password>     
        <phone>(04) 2288-1122</phone>   
    </user>  
</users>
